/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountInfo: typeof import('./src/components/TradingComponents/AccountInfo.vue')['default']
    AddLiquidity: typeof import('./src/components/LiquidityComponents/AddLiquidity.vue')['default']
    AlgorandAddress: typeof import('./src/components/AlgorandAddress.vue')['default']
    AsaChart: typeof import('./src/components/TradingComponents/AsaChart.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/LiquidityComponents/RemoveLiquidity copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MarketDepth: typeof import('./src/components/TradingComponents/MarketDepth.vue')['default']
    MarketOrder: typeof import('./src/components/TradingComponents/MarketOrder.vue')['default']
    MyLiquidity: typeof import('./src/components/LiquidityComponents/MyLiquidity.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PoolSwap: typeof import('./src/components/LiquidityComponents/PoolSwap.vue')['default']
    RemoveLiquidity: typeof import('./src/components/LiquidityComponents/RemoveLiquidity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
