<script setup lang="ts">
import Layout from '@/layouts/PublicLayout.vue'
import Card from 'primevue/card'
import Button from 'primevue/button'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { getCurrentLocale } from '@/i18n'
import { getHelpUseCase, getHelpUseCasesByCategory } from '@/data/helpUseCases'

const { t, locale } = useI18n()
const route = useRoute()
const router = useRouter()

const slug = computed(() => String(route.params.useCaseSlug ?? ''))
const useCase = computed(() => getHelpUseCase(slug.value))

const key = (suffix: string) => `views.help.useCases.${slug.value}.${suffix}`

/** Steps are stored as a single newline-separated string for reliable i18n fallback. */
const steps = computed<string[]>(() => {
  if (!useCase.value) return []
  const raw = t(key('steps'))
  if (!raw || raw === key('steps')) return []
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
})

const related = computed(() => {
  if (!useCase.value) return []
  return getHelpUseCasesByCategory(useCase.value.category).filter(
    (item) => item.slug !== slug.value
  )
})

// Localized overview screenshot generated by scripts/generate-help-screenshots.mjs:
//   help-screenshots/<locale>/<slug>/overview.png
const shotBase = () => {
  const base = import.meta.env.BASE_URL ?? '/'
  return `${base}help-screenshots/${getCurrentLocale()}/${slug.value}`
}

const overviewFailed = ref(false)
const overviewUrl = computed(() => `${shotBase()}/overview.png`)

// Reset the overview fallback whenever the guide or language changes.
watch(
  [slug, locale],
  () => {
    overviewFailed.value = false
  },
  { immediate: true }
)

const goToFeature = () => {
  if (useCase.value) router.push(useCase.value.screenshotRoute)
}
</script>

<template>
  <Layout>
    <div class="w-full max-w-4xl mx-auto">
      <!-- Unknown slug -->
      <Card v-if="!useCase" class="mb-2">
        <template #content>
          <div class="m-3 text-center">
            <i class="pi pi-exclamation-triangle text-3xl text-muted" />
            <p class="mt-3 text-muted">{{ t('views.help.notFound') }}</p>
            <RouterLink to="/help">
              <Button :label="t('views.help.backToHelp')" icon="pi pi-arrow-left" text />
            </RouterLink>
          </div>
        </template>
      </Card>

      <template v-else>
        <RouterLink to="/help" class="help-back">
          <i class="pi pi-arrow-left" />
          <span>{{ t('views.help.backToHelp') }}</span>
        </RouterLink>

        <Card class="mb-2">
          <template #content>
            <div class="m-3 help-detail">
              <div class="flex items-start gap-3 mb-2">
                <span class="help-detail-icon">
                  <i :class="useCase.icon" />
                </span>
                <div>
                  <div class="help-detail-category">
                    {{ t(`views.help.categories.${useCase.category}`) }}
                  </div>
                  <h1>{{ t(key('title')) }}</h1>
                </div>
              </div>

              <p class="help-detail-intro">{{ t(key('intro')) }}</p>

              <Button
                :label="t('views.help.openFeature')"
                icon="pi pi-external-link"
                size="small"
                class="mb-4"
                @click="goToFeature"
              />

              <!-- Localized overview screenshot (hidden until generated) -->
              <figure v-if="!overviewFailed" class="help-screenshot">
                <img
                  :src="overviewUrl"
                  :alt="t(key('title'))"
                  loading="lazy"
                  @error="overviewFailed = true"
                />
              </figure>

              <template v-if="steps.length">
                <h2>{{ t('views.help.stepsTitle') }}</h2>
                <ol class="help-steps">
                  <li v-for="(step, index) in steps" :key="index" class="help-step">
                    <div class="help-step-text">{{ step }}</div>
                  </li>
                </ol>
              </template>

              <div class="help-tip">
                <i class="pi pi-lightbulb" />
                <div>
                  <strong>{{ t('views.help.tipTitle') }}</strong>
                  <span>{{ t(key('tip')) }}</span>
                </div>
              </div>
            </div>
          </template>
        </Card>

        <Card v-if="related.length" class="mb-2">
          <template #content>
            <div class="m-3">
              <h2 class="help-related-title">{{ t('views.help.relatedTitle') }}</h2>
              <div class="flex flex-col gap-2">
                <RouterLink
                  v-for="item in related"
                  :key="item.slug"
                  :to="`/help/${item.slug}`"
                  class="help-related-link"
                >
                  <i :class="item.icon" />
                  <span>{{ t(`views.help.useCases.${item.slug}.title`) }}</span>
                  <i class="pi pi-angle-right ml-auto" />
                </RouterLink>
              </div>
            </div>
          </template>
        </Card>
      </template>
    </div>
  </Layout>
</template>

<style scoped>
.help-back {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  margin: 0.25rem 0 0.5rem 0.25rem;
  color: var(--text-muted);
  font-weight: 600;
  font-size: 0.9rem;
}
.help-back:hover {
  color: var(--brand);
}
.help-detail h1 {
  font-size: 1.6rem;
  font-weight: 700;
}
.help-detail h2 {
  font-size: 1.2rem;
  font-weight: 650;
  margin-top: 1.75rem;
  margin-bottom: 0.75rem;
  padding-top: 1.25rem;
  border-top: 1px solid var(--surface-border);
}
.help-detail-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex: 0 0 auto;
  width: 2.8rem;
  height: 2.8rem;
  border-radius: 0.7rem;
  background: var(--surface-inset);
  color: var(--brand);
  font-size: 1.3rem;
}
.help-detail-category {
  text-transform: uppercase;
  letter-spacing: 0.05em;
  font-size: 0.72rem;
  font-weight: 700;
  color: var(--brand);
}
.help-detail-intro {
  color: var(--text-muted);
  max-width: 72ch;
  margin-bottom: 1rem;
  line-height: 1.5;
}
.help-screenshot {
  margin: 0 0 0.5rem;
  border: 1px solid var(--surface-border);
  border-radius: 0.75rem;
  overflow: hidden;
  background: var(--surface-inset);
}
.help-screenshot img {
  display: block;
  width: 100%;
  height: auto;
}
.help-steps {
  list-style: decimal;
  padding-left: 1.4rem;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}
.help-steps li {
  color: var(--text-color);
  line-height: 1.45;
  padding-left: 0.25rem;
}
.help-step-text {
  max-width: 74ch;
}
.help-tip {
  display: flex;
  gap: 0.6rem;
  align-items: flex-start;
  margin-top: 1.75rem;
  padding: 0.9rem 1rem;
  border-radius: 0.7rem;
  border: 1px solid var(--surface-border);
  background: var(--surface-inset);
}
.help-tip .pi-lightbulb {
  color: var(--brand);
  margin-top: 0.15rem;
}
.help-tip strong {
  display: block;
  margin-bottom: 0.2rem;
}
.help-tip span {
  color: var(--text-muted);
  line-height: 1.45;
}
.help-related-title {
  font-size: 1.1rem;
  font-weight: 650;
  margin-bottom: 0.75rem;
}
.help-related-link {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  padding: 0.65rem 0.85rem;
  border-radius: 0.6rem;
  border: 1px solid var(--surface-border);
  background: var(--surface-card);
  font-weight: 600;
  transition: border-color 0.2s ease;
}
.help-related-link:hover {
  border-color: var(--brand);
  color: var(--brand);
}
</style>
